const CardsAPI = {
  cards: [
    { advice: "Remove specifics and convert to ambiguities"},
    { advice: "Think of the radio"},
    { advice: "Don't be frightened of clichés"},
    { advice: "Allow an easement (an easement is the abandonment of a stricture"},
    { advice: "What is the reality of the situation"},
    { advice: "Simple subtraction"},
    { advice: "Are there sections? Consider transitions"},
    { advice: "Turn it upside down"},
    { advice: "Go slowly all the way round the outside"},
    { advice: "A line has two sides"},
    { advice: "Infinitesimal graditions"},
    { advice: "Make an exhaustive list of everything you might do and do the last thing on the list"},
    { advice: "Change instrument roles"},
    { advice: "Into the impossible"},
    { advice: "Accretion"},
    { advice: "Ask people to work against their better judgement"},
    { advice: "Disconnect from desire"},
    { advice: "Take away the elements in order of apparent non-importance"},
    { advice: "Emphasize repetitions"},
    { advice: "Don't be afraid of things because they're easy to do"},
    { advice: "Is there something missing?"},
    { advice: "Don't be frightened to display your talents"},
    { advice: "Use unqualified people"},
    { advice: "Breathe more deeply"},
    { advice: "How would you have done it?"},
    { advice: "Honor thy error as a hidden intention"},
    { advice: "Emphasize differences"},
    { advice: "Only one element of each kind"},
    { advice: "Do nothing for as long as possible"},
    { advice: "Bridges: -build -burn"},
    { advice: "Water"},
    { advice: "You don't have to be ashamed of using your own ideas"},
    { advice: "Make a sudden, destructive upredictable action; incorporate"},
    { advice: "Tidy up"},
    { advice: "Consult other sources"},
    { advice: "Do the words need changing?"},
    { advice: "Use an unacceptable color"},
    { advice: "Ask your body"},
    { advice: "Humanize something free of error"},
    { advice: "Use filters"},
    { advice: "Balance the consistency principle with the inconsistency principle"},
    { advice: "Fill every beat with something"},
    { advice: "Do nothing for as long as possible"},
    { advice: "Discard an axiom"},
    { advice: "Listen to the quiet voice"},
    { advice: "What wouldn't you do?"},
    { advice: "Is it finished?"},
    { advice: "Decorate, decorate"},
    { advice: "Put in earplugs"},
    { advice: "Give the game away"},
    { advice: "Reverse"},
    { advice: "Abandon normal instruments"},
    { advice: "Trust in the you of now"},
    { advice: "Use fewer notes"},
    { advice: "What would your closest friend do?"},
    { advice: "Repetition is a form of change"},
    { advice: "Distorting time"},
    { advice: "Give way to your worst impulse"},
    { advice: "Make a blank valuable by putting it in an exquisite frame"},
    { advice: " "},
    { advice: "The inconsistency principle"},
    { advice: "Ghost echoes"},
    { advice: "Don't break the silence"},
    { advice: "You can only make one dot at a time"},
    { advice: "Discover the recipes you are using and abandon them"},
    { advice: "Just carry on"},
    { advice: "Cascades"},
    { advice: "(Organic) machinery"},
    { advice: "Courage!"},
    { advice: "What mistakes did you make last time?"},
    { advice: "You are an engineer"},
    { advice: "Consider different fading systems"},
    { advice: "Remove ambiguities and convert to specifics"},
    { advice: "Mute and continue"},
    { advice: "Look at the order in which you do things"},
    { advice: "It is quite possible (after all)"},
    { advice: "Go outside. Shut the door."},
    { advice: "Don't stress one thing more than another"},
    { advice: "Do we need hole?"},
    { advice: "Cluster analysis"},
    { advice: "Work at a different speed"},
    { advice: "Do something boring"},
    { advice: "Look closely at the most embarrassing details and amplify them"},
    { advice: "Define an area as 'safe' and use it as an anchor"},
  ],
