const CardsAPI = [
    "Remove specifics and convert to ambiguities",
    "Think of the radio",
    "Don't be frightened of clichés",
    "Allow an easement (an easement is the abandonment of a stricture)",
    "What is the reality of the situation",
    "Simple subtraction",
    "Are there sections? Consider transitions",
    "Turn it upside down",
    "Go slowly all the way round the outside",
    "A line has two sides",
    "Infinitesimal graditions",
    "Make an exhaustive list of everything you might do and do the last thing on the list",
    "Change instrument roles",
    "Into the impossible",
    "Accretion",
    "Ask people to work against their better judgement",
    "Disconnect from desire",
    "Take away the elements in order of apparent non-importance",
    "Emphasize repetitions",
    "Don't be afraid of things because they're easy to do",
    "Is there something missing?",
    "Don't be frightened to display your talents",
    "Use unqualified people",
    "Breathe more deeply",
    "How would you have done it?",
    "Honor thy error as a hidden intention",
    "Emphasize differences",
    "Only one element of each kind",
    "Do nothing for as long as possible",
    "Water",
    "You don't have to be ashamed of using your own ideas",
    "Make a sudden, destructive unpredictable action; incorporate",
    "Tidy up",
    "Consult other sources",
    "Do the words need changing?",
    "Use an unacceptable color",
    "Ask your body",
    "Humanize something free of error",
    "Use filters",
    "Balance the consistency principle with the inconsistency principle",
    "Fill every beat with something",
    "Do nothing for as long as possible",
    "Discard an axiom",
    "Listen to the quiet voice",
    "What wouldn't you do?",
    "Is it finished?",
    "Decorate, decorate",
    "Put in earplugs",
    "Give the game away",
    "Reverse",
    "Abandon normal instruments",
    "Trust in the you of now",
    "Use fewer notes",
    "What would your closest friend do?",
    "Repetition is a form of change",
    "Distorting time",
    "Give way to your worst impulse",
    "Make a blank valuable by putting it in an exquisite frame",
    "The inconsistency principle",
    "Ghost echoes",
    "Don't break the silence",
    "You can only make one dot at a time",
    "Discover the recipes you are using and abandon them",
    "Just carry on",
    "Cascades",
    "(Organic) machinery",
    "Courage!",
    "What mistakes did you make last time?",
    "You are an engineer",
    "Consider different fading systems",
    "Remove ambiguities and convert to specifics",
    "Mute and continue",
    "Look at the order in which you do things",
    "It is quite possible (after all)",
    "Go outside. Shut the door.",
    "Don't stress one thing more than another",
    "Do we need a hole?",
    "Cluster analysis",
    "Work at a different speed",
    "Do something boring",
    "Look closely at the most embarrassing details and amplify them",
    "Define an area as 'safe' and use it as an anchor"
  ]

  export default CardsAPI
